apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: alexantopipelinesjavascriptdocker
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
     apiVersion: extensions/v1beta1
     kind: Deployment
     name: alexantopipelinesjavascriptdocker
  targetCPUUtilizationPercentage: 10 
