apiVersion: v1
kind: Service
metadata:
    name: alexantopipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8090 
    selector:
        app: alexantopipelinesjavascriptdocker